task: create
host: "https://islandora.example.com"
username: "islandora user name" 
password: "islandora password" 
input_dir: test_data/
input_csv: input.csv
output_csv: output.csv

subdelimiter: "^||^"

allow_adding_terms: true
allow_missing_files: true

timestamp_rollback: true

log_response_body: false